### ISSUE TITLE
Counter clockwise and E->S->W->N

### ISSUE THREAD

**Issue by coderdojortp** [ecc521/mahjong#1]
Switch play to be counterclockwise.  Start with E->S->W->N.  Fix imagery - maybe even don't use a compass since its not a compass...

**Comment by ecc521** [comment]
Not a priority for now, as it doesn't affect gameplay, and is functionally the same.

**Comment by ecc521** [comment]
Also, the existing gameplay IS E->S->W->N. What is the problem there?

**Comment by coderdojortp** [comment]
The visualization.  The next turn should be the person to my right.  So, the wrong hand is flashing from the perspective of someone used to mahjong.  Also, after a charleston, it means the person first throw is likely to just be throwing you what you gave them in the last round.   Since the winds are not the traditional winds from a compass, you'll also want a different image than a compass.   Though it doesn't really matter for family/friends, it will be an instant loss of credibility with anyone who is a real mahjong player who looks at it.

**Comment by ecc521** [comment]
Implemented.
