### ISSUE TITLE
Prevent/recover from accidental "next turn" instead of "place tiles"

### ISSUE THREAD

**Issue by coderdojortp** [ecc521/mahjong#10]
If someone is trying to make a play (ie drags a pong out), but hits next turn instead of place tiles, provide some type of recovery.  In a "real" game, they would say pong and put out the tiles.  Either prevent them from doing "next turn" if they have a pong laid out, or have an "undo" button, or similar.   Or, consider whether you really even need two different buttons.

**Comment by ecc521** [comment]
Implemented as of afb34de
