### ISSUE TITLE
Eliminate Disable Automatic Sorting double negative (replace with Automatic Sorting, defaulted yes)

### ISSUE THREAD

**Issue by ecc521** [ecc521/mahjong#101]
Could get confusing in other languages. Rewrite the code and migrate the setting.

**Comment by ecc521** [comment]
@Miles-Mom
How would you recommend translating "Auto-Sort Tiles: "?

(Google is saying 自动排序瓷砖, but I'd like to have this one checked)


And also, an explanation for the weirdness with the naming:
The setting was initially intended to be named "Insert Tiles at End", however when I implemented it, it entirely disabled sorting instead of just inserting at end (which was a totally acceptable behavior given the setting's use case, and changing to the expected behavior would have been incredibly hard), so I just renamed the display "Disable Auto Sort". 

That's how the double negative happened.

**Comment by ecc521** [comment]
Implemented in a19a6cb. Just waiting on translation (no rush :)

**Comment by Miles-Mom** [comment]
Sorry i just saw this. 
this is what's in the zh.json "Disable Auto-Sort: " : "不自动将牌排序位: ",
you can replace it with "Auto-Sort Tiles: " : "自动将牌排序位: ",

**Comment by Miles-Mom** [comment]
@ecc521

**Comment by ecc521** [comment]
Completed in 8f252a2
