### ISSUE TITLE
Locale should not read from save file

### ISSUE THREAD

**Issue by ecc521** [ecc521/mahjong#110]
Using locale from save files should not be done.

**Comment by ecc521** [comment]
Blocking #99 
Save files use the locale from the save file, or crash if none specified (for the client). 
We should use the locale of the device loading the save file.

**Comment by ecc521** [comment]
The crash bug was fixed in db920d9. 
The locale of the save file, rather than the client, is still used however.

**Comment by ecc521** [comment]
Perhaps a format switch? Store the room details rather than server details? That would lose names, however. 
Or maybe a way to initialize clients, then initialize games? 
Either way, the current initialization doesn't work. 

Perhaps hold initialization until after clients set up?

**Comment by ecc521** [comment]
I think the fundamental issue is that with a save file, the Client object really refers to different clients depending on who is loading the save file. 

Save Files are I believe the only real situation that this can happen.

**Comment by Miles-Mom** [comment]
i am back too. will try to use the feature. top of my head idea: is there a phrase that we know will for sure be in the saved file, if so, then detect which locale the file was, and decide what to do?

**Comment by ecc521** [comment]
Should be fixed in c402f8d
