### ISSUE TITLE
Localization Release

### ISSUE THREAD

**Issue by ecc521** [ecc521/mahjong#111]
Release is pending on the following:

~- [ ] Display Name Localization (arrgh... Time to change Simulator locales)~
- [x] iOS App Build (easy)
- [x] iOS App Approval (probably 24 hours, but has fluctuated wildly in past, and process was streamlined recently)
- [x] Android App Build (easy)
- [x] Maintenance Alert (want to leave it out for at least a few hours)
- [x] Sufficient Testing (by the time everything else happens, we will be here)

Once all are met, I'll release localization (and hopefully the world won't end)
I don't think Apple reviews on weekends, but they've massively revamped their process, so I really don't know what will happen.

**Comment by Miles-Mom** [comment]
Go Tucker the Tiger!!!

**Comment by ecc521** [comment]
@Miles-Mom 

One more thing to add:
Display name needs to be localized (it's no longer Mahjong 4 Friends, but 麻将合家福)
That'll take me a bit of time to sort out. I'm thinking Monday or Tuesday before I actually click all the release buttons most likely.

**Comment by Miles-Mom** [comment]
@ecc521 What if you hold off updating the localized App name until later? So I can continue working with my friends on the best of the best names. 

If you need to update, 合家福麻将  is better for actual app name (i assume in the store listings). Note the sequence change.

**Comment by Miles-Mom** [comment]
If it is easy to update then change it, and we update later. I assumed it would be hassle.

**Comment by ecc521** [comment]
I was wondering if you would say change the sequence :)

**Comment by ecc521** [comment]
Agreed on the app name - it's looking annoying, so I'll hold for now.

**Comment by Miles-Mom** [comment]
Do you know that Feb 1st is the Chinese new year? The year of the Tiger, Tucker the Tiger :-)

**Comment by ecc521** [comment]
Release scheduled for 7:30 PM EST. Closing this issue.
