### ISSUE TITLE
Minor localization improvements after release

### ISSUE THREAD

**Issue by Miles-Mom** [ecc521/mahjong#112]
Parking lot of minor localization issues noticed during our continued testing: 

- [x ] "waiting on: " translation needed, this shows up only when multiple non-bot players present
- [x ] translation "作为东风，你先出牌。 选择一张牌, 然后按'继续'。" perhaps it should be: as East seat (dong ja), not East Wind, (dong feng)
- [x ] use 开/关for yes/no. Confirmed with a few.
- [x ] 不是吃也不是碰或扛 typo.
- [x ] enter room should be for either join room (already existing) and create room (yet to exist)
- [x ] 福了🏆 idea, or, 福了！(胡, 和, 刻)
- [x ] 最多个顺子look into
加入桌子, or, 加入游戏桌?

- [ x] 合家福 +5 vs 朋友圈 +0 - winner declared.

**Comment by Miles-Mom** [comment]
Some variations of testing matrix:
* tested with diff browsers (IE, Firefox, Chrome, Androids, Windows), local and remote, 
* tested default locale being 4 zh's, en
* Chinese mahjong, defaults all in, defaults all out
* American mahjong, not knowing the rule details, random picking, including Other Cards

**Comment by Miles-Mom** [comment]
how to assign myself?

**Comment by ecc521** [comment]
I assume IE breaks? (Not worried if it does)

**Comment by ecc521** [comment]
I wouldn't worry about testing Other Card, or anything but the newest NMJL/Marvelous. Honestly, Marvelous only is probably fine - if Marvelous works, NMJL almost certainly will

**Comment by Miles-Mom** [comment]
IE worked fine.

**Comment by ecc521** [comment]
To download a save file, reload page/app and click download icon next to resume button (Single Player/Offline games only)

To upload, click use save file and upload that file

To use a tutorial file.. watch a tutorial video and they'll show you :)

**Comment by ecc521** [comment]
IE? Or edge?

If IE seriously worked... Wow!

**Comment by Miles-Mom** [comment]
one tiny half sentence was not translated, only ONE peculiar situation. Putting in parking lot, will track down where later. testing adnausea more now.

**Comment by Miles-Mom** [comment]
You are right. Edge, not IE. i used the word colloquially, wrong.

**Comment by ecc521** [comment]
There you go.
