### ISSUE TITLE
App Updates not working

### ISSUE THREAD

**Issue by ecc521** [ecc521/mahjong#114]
i18n is never imported
@Miles-Mom: I'll fix this. But oopsies!

**Comment by ecc521** [comment]
Fixed in 714da5d

**Comment by ecc521** [comment]
This is non-critical. I'll mitigate with a displayMessage, rather than pushing out a new update. 
The code is fixed for future releases.

**Comment by Miles-Mom** [comment]
But it works for me already.

I am on Android, didn't update the Google play even.

**Comment by ecc521** [comment]
Is the settings icon broken :)
Some things update without an app update, other things don't!

**Comment by Miles-Mom** [comment]
Only the settings icon, but all locale etc worked marvelously ( knock on
🪵🪵🪵)

**Comment by ecc521** [comment]
The title of this issue is bad (sounds more severe than it is). The commit name is much more accurate. 
Google is taking longer to review than I'm used to (though I should've submitted about 20 minutes ahead, not 5)

Once the Android update is out, the settings icon will come back.

**Comment by ecc521** [comment]
And yep. No issues here yet, though it's a bit early.

**Comment by ecc521** [comment]
I'll see if the bandwidth comes down. I snuck caching changes and more into the localization branch before the merge, so I can blame all my bugs on you!

**Comment by Miles-Mom** [comment]
That'll make me proud :)

When I was at work, I used to tell my team that those who work the most and
on the toughest tasks will most likely, simple math, to get the most/worst
bugs, so think of it as a badge of honor :)

At least I am productive of something :)
