### ISSUE TITLE
Translation Bugs

### ISSUE THREAD

**Issue by ecc521** [ecc521/mahjong#123]
Issues include use of the localizeMessage format on the client side, but not in a client object, where it does not work and instead returns undefined. 

I will be doing significant refractoring, including changing the callback system to avoid binding, and offering the localizeMessage format on the i18n instance itself, instead of making specific to the client.

**Comment by ecc521** [comment]
This includes "undefined" when clicking a tile in the placemat.

**Comment by ecc521** [comment]
Fixed in 49e4b5c

**Comment by ecc521** [comment]
@Miles-Mom 
You may want to take a look at what I did here. I don't think this needs any review, but if you do make changes in the future, this is a big adjustment. 

i18n.localizeMessage now allows the same formatting as the previous ClientObj.localizeMessage did - so there is far more flexibility for translating messages client side.

**Comment by Miles-Mom** [comment]
Absolutely love it!!!

I am indifferent to the override, want to say yes since it will be SO Much more flexible, but then we should test thoroughly again and so far the client side worked okay. so may be we let the sleeping good dog lie, until when the itch needs to be scratched? May be we are thinking the same :-)

**Comment by ecc521** [comment]
I'll take a glance at it - assuming that localizeMessage always handles strings the same as i18n.__ would (ie, passthrough untouched), any change should either work perfectly or fail catastrophically.

**Comment by ecc521** [comment]
Alright, we can't overload i18n.__

They are not compatible.

**Comment by ecc521** [comment]
See RoomManager.js:789
