### ISSUE TITLE
Seating positions and East wind movement to mirror official rules

### ISSUE THREAD

**Issue by coderdojortp** [ecc521/mahjong#18]
Provide an option to mimic exactly how the game is played around a table.  Official rules the players keep the same seats through out.  East wind moves one position counter-clockwise per hand unless the dealer (east) wins.  If east wins, they can optionally chose to maintain east wind.

**Comment by ecc521** [comment]
This should be done.
Optional isn't really there, however one can always start and end another game to do that.
