### ISSUE TITLE
Support for American Mahjong

### ISSUE THREAD

**Issue by coderdojortp** [ecc521/mahjong#6]
Add minimal support to allow American mahjong:
1. add jokers
2.allow up to 3 charlestons
3. pretties stay in hand
4. can place group of up to 5(?) tiles - need to see what is most that go at once on a card
5. do not score
6. do autopick up kongs
7. do not do calling
8. do not verify mahjong   

I'm sure there's more - but I think toleration is more not doing stuff than actually doing stuff to allow "dumb" American mahjong.  Basically - just the game board without the intelligence.  Tell them what's been thrown, and what they pickup, but don't do any checking.

**Comment by ecc521** [comment]
The provided "toleration" changes are far too little to even tolerate the game, much less play it, due to things such as joker swapping. Providing toleration support would not be significantly harder than providing full support, and both of which require significant changes.

**Comment by ecc521** [comment]
This issue is suspended indefinitely while other priorities are accomplished.

**Comment by ecc521** [comment]
Implemented
