### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ecc521** [ecc521/mahjong#99]
Running list of significant issues with localization:

Blocking:
- [x] Make changing language more intuitive (there is no indication that the menu must be closed - we should be clear about that, or provide a button to "update language", aka reload page). Mini-sync button?
- [x] Building new app release, ensuring all modules in, etc. Probably want to block this on #95 (assuming it is relatively easy). 
- [x] Confirm window.navigator works with native apps (might need to read from Capacitor when native)
- [x] App Signing - Current developer certificate is expired, so it could take a few hours to sort out the build. 
- [x] Sort out iOS App Category (EDIT: No real issue here - category is correct, just appeared under Other due to too few games for category? Appears correct on other devices, so assuming correct. )
- [x] Chinese language svgs to app stores
- [x] Changing language once in the room does not work (language is only set when joining the room) - this should be an easy fix (send in getCurrentRoom or something - just need to look at it)
- [x] Language dropdown should probably be made slightly larger - apply some CSS to increase by 25% or something
- [x] Number translations - most numbers don't appear to be translated, like in "Bot 1", or in (3/4). Should this be changed?
- [x] "Saved Game:" needs to be translated if possible. This is a front page item. 
- [x] Message translations do not appear to work server-side for offline games (I'll investigate this one)

Non-blocking:
- [x] #101 is probably a good change to make as well. 
- [x] Need some sort of plan for translating tip of the day (can simply disable if not English, sort out translations for it at some later point)

**Comment by Miles-Mom** [comment]
Hi Tucker - if it is checked does that mean you are working on it? I was just now looking into item2 and saw your checking the box.

The Saved Game: is already translated, it was just the i18n.__() enclosure in the code was lost in my multiple merge attempts. 

On numbers, For the most part, we need not translate the number, only for things special. The 3/4 etc we definitely do not translate. For "1 circle" etc, we definitely needed to translate. On the Bot #, i didn't translate because the random number... but now i think it can't be more than 4, and I should translate to someone REALLY cool, to first attempt to translate the Chinese A/B/C/D system, to "机器人/Bot" 甲/乙/丙/丁, and if they are out side of my range, then default to the "Bot#". Let me work on that...

I thought of talking to you about Tips on a on-going basis. Want to propose: 1) use Google translate (if they have a online API), unless, we have a translate by ourselves, which, as long as I am around, should not be problem.

**Comment by Miles-Mom** [comment]
@ecc521 I probably needed this first.

**Comment by ecc521** [comment]
@Miles-Mom 
Everything I've checked off is something I have completed. 
I'll update things to incorporate what you just mentioned. One minute.

**Comment by ecc521** [comment]
Bots are 1, 2, and 3, unless users rename them. 
There is no way to have 4 bots (unless you go into the developer console and directly call addBot - I believe it will work then, they just won't play)

**Comment by ecc521** [comment]
@Miles-Mom 
I'll fix #101, and sort out the app stuff, so if you'd like to make the language changing a bit more intuitive, you have a good bit of time before I get to it (probably not getting there this weekend)

**Comment by Miles-Mom** [comment]
@ecc521 I did a miniSync button as well as an info label for the reloading. But mine are both WAY TOO ugly :( i also played with the styles in code which i think it is bad to start with. I don't like my code FYI :-( Also, EVERYTHING in the setting (not just language, and Game Setting same as General Setting) will be applied after close, right? So maybe nothing needs to be done?

**Comment by ecc521** [comment]
@Miles-Mom 
All other settings are applied immediately - the impact just isn't noticeable until some other action is performed. 
The reason the reload is necessary is because we don't update existing text (that's WAYYYY too complex)

I'll take a look - I have an idea or two.

**Comment by ecc521** [comment]
Implemented in f1a623f

**Comment by ecc521** [comment]
Alright - question for maintenance messages:

I use setStaticMessageBar (and immediately before maintenances, messageAllServerClients) - these functions are defined in server/server.js

How would you recommend handling different locales? I'm thinking it's probably best to adjust those functions to take messages for all locales, then send out the appropriate one?

Wondering if you might have any better ideas here.

**Comment by ecc521** [comment]
Migrated non-blocking components to #105

**Comment by ecc521** [comment]
Alright - done again for tonight. May or may not finish the app update tomorrow. 
I'm going to remove figuring out maintenance messages from blocking this PR. That can be handled later, as English messages will still work (and we could always put both in one message for now).

**Comment by Miles-Mom** [comment]
Agreed. 1) English will always work. I actually think putting both locale in is excellent. Almost like the tips for folks to know the goodies  :)  2) I share your idea of sending messages with all locales, and the code to dispatch them accordingly. To deal with the adhoc nature. 3) I think we can also put the commonly used ones in our locale file also, like the maintenance coming in ## minutes etc, so if local is not provided but needed, we try look it up. 4) messageAllServerClients eventually goes to displayMessages, which we do attempt to look up for locale translation, body and title.  5) the key is to move the dynamic data out of the strings. so long we can do that, else is easier. 

Good night.

**Comment by ecc521** [comment]
Alright - iOS seems to be going pretty smoothly, haven't started Android testing yet. 
Not seeing any significant issues. The screen does temporarily go white when changing language - might want to display splashscreen in intermission or something, but otherwise all good.

**Comment by ecc521** [comment]
I believe everything blocking is now completed. I'll be doing some significant testing now, then releasing.
